#pragma once

#define GZ_GAME_PROPERTY_FLAG_WINDOW				0x0001
#define GZ_GAME_PROPERTY_FLAG_DX_FILE				0x0002
#define GZ_GAME_PROPERTY_FLAG_GL_FILE				0x0004
#define GZ_GAME_PROPERTY_FLAG_GAME_SIZE				0x0008
#define GZ_GAME_PROPERTY_FLAG_GPU_MEMORY			0x0010
#define GZ_GAME_PROPERTY_FLAG_GPU_LOAD_INTERVAL		0x0020


#define CHECK_GPU_LOAD_TIME_S 5000
#define CHECK_GPU_LOAD_TIME_S1 1000
#define CHECK_GPU_LOAD_TIME_L 25000


#define GZ_GAME_DGPU_LOAD_MIN  15
#define GZ_GAME_IGPU_LOAD_MIN	  25